# Generated by Django 5.1.15 on 2026-08-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1)),
                ('car_type', models.CharField(choices=[('sedan', '세단'), ('suv', 'SUV'), ('truck', '화물차'), ('compact', '경차')], max_length=20)),
                ('car_age', models.PositiveIntegerField(default=0)),
                ('passenger', models.CharField(blank=True, choices=[('alone', '혼자'), ('family', '가족'), ('vulnerable', '노약자'), ('friend', '친구')], max_length=20, null=True)),
                ('load_kg', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
